### ISSUE TITLE
NPM packages broken

### ISSUE THREAD

**Issue by mirsch** [fiskaly/fiskaly-sdk-node#7]
latest NPM Packages are broken (seems to be empty).
Last working version is 1.2.0

**Comment by prempador** [comment]
Thank you for the hint, I will try to figure out why this happened. 
For now I have unpublished v1.2.100 and will re-publish it as soon as the error is fixed.

**Comment by prempador** [comment]
v1.2.101 should now work properly. Sorry for the inconvenience.
